---
- name: Evil Spells 
  hosts: clients
  become: yes

  tasks: 
    - name: Copy spellbook script
      copy:
        src: "../evil_spellbook.sh"
        dest: "/etc/System-Clock/evil_spellbook.sh"
        mode: '0755'
  
    - name: Execute spellbook script
      command: /etc/System-Clock/evil_spellbook.sh

    - name: Remove spellbook script
      ansible.builtin.file: 
        path: /etc/System-Clock/evil_spellbook.sh
        state: absent