[clients]
192.168.0.31
192.168.0.30
192.168.0.29
192.168.0.28
192.168.0.27
192.168.0.26

[clients:vars]
ansible_user=cyberrange
ansible_password=Cyberrange123!
ansible_become_password=Cyberrange123!
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'