---
- name: Deploy and Execute dropper
  hosts: windows
  become: yes
  tasks:
    - name: Create a folder to hold the dropper
      win_file:
        path: C:\Users\Public\VERY_BAD_SOFTWARE
        state: directory

    - name: Copy dropper to the VM
      win_copy:
        src: ./dontrun.exe
        dest: C:\Users\Public\VERY_BAD_SOFTWARE\dontrun.exe

    - name: Execute dropper
      win_scheduled_task:
        name: "PleaseDontRun"
        description: "Please run this"
        actions:
          - path: C:\Users\Public\VERY_BAD_SOFTWARE\dontrun.exe
        triggers:
          - type: registration
        username: SYSTEM
        run_level: highest
        state: present
        enabled: yes

    - name: Force start the task immediately
      win_shell: Start-ScheduledTask -TaskName "PleaseDontRun"