---
- name: Deploy and Execute dropper
  hosts: windows
  tasks:
    - name: Create a folder to hold the dropper
      win_file:
        path: C:\Users\Public\VERY_BAD_SOFTWARE
        state: directory

    - name: Copy dropper to the VM
      win_copy:
        src: ./dontrun.exe
        dest: C:\Users\Public\VERY_BAD_SOFTWARE\dontrun.exe
    
    - name: Execute dropper with Admin permissions
      win_shell: .\dontrun.exe
      args:
        chdir: C:\Users\Public\VERY_BAD_SOFTWARE
      become: yes
      become_method: runas
      become_user: Administrator