w:
	x86_64-w64-mingw32-gcc winmain.c libs/wheelswap.c libs/winencode.c libs/winexfil.c libs/winkeylog.c libs/winvbs.c -I./libs -I. -o main.exe -lcrypt32 -lws2_32 -mwindows -lbcrypt -lgdi32 -luser32 -s