[blue_team]
192.168.0.26
192.168.0.27
#10.1.1.7
#10.2.1.7
#etc

[blue_team:vars]
#change these
ansible_user=cyberrange
ansible_password=Cyberrange123!
#ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_become_password=Cyberrange123!
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

