[windows_servers]
192.168.0.24

[windows_servers:vars]
ansible_user=Administrator
ansible_password=Cyberrange123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
