[windows_servers]
# server01.corp.local
# server02.corp.local

[windows_servers:vars]
ansible_user=Administrator
ansible_password=CHANGE_ME
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
