[windows_servers]
10.2.1.3

[windows_servers:vars]
ansible_user=Administrator
ansible_password=redredred123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
