[clients]
10.1.1.4
10.1.1.5
10.1.1.6
10.1.1.7
10.1.1.8
10.1.1.9

10.2.1.4
10.2.1.5
10.2.1.6
10.2.1.7
10.2.1.8
10.2.1.9

[clients:vars]
ansible_user=crimsonteam
ansible_password=crims0nwinz!
ansible_become_password=crims0nwinz!
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'